config/routes.rb
Rails.application.routes.draw do
  resources :resource_names
  root 'resource_names#index'

end

app/models/resource_name.rb
class ResourceName < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/resource_names_controller.rb
class ResourceNamesController < ApplicationController
  before_action :set_resource_name, only: [:show, :edit, :update, :destroy]

  # GET /resource_names
  # GET /resource_names.json
  def index
    @resource_names = ResourceName.all
  end

  # GET /resource_names/1
  # GET /resource_names/1.json
  def show
  end

  # GET /resource_names/new
  def new
    @resource_name = ResourceName.new
  end

  # GET /resource_names/1/edit
  def edit
  end

  # POST /resource_names
  # POST /resource_names.json
  def create
    @resource_name = ResourceName.new(resource_name_params)

    respond_to do |format|
      if @resource_name.save
        format.html { redirect_to @resource_name, notice: 'Resource name was successfully created.' }
        format.json { render :show, status: :created, location: @resource_name }
      else
        format.html { render :new }
        format.json { render json: @resource_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resource_names/1
  # PATCH/PUT /resource_names/1.json
  def update
    respond_to do |format|
      if @resource_name.update(resource_name_params)
        format.html { redirect_to @resource_name, notice: 'Resource name was successfully updated.' }
        format.json { render :show, status: :ok, location: @resource_name }
      else
        format.html { render :edit }
        format.json { render json: @resource_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resource_names/1
  # DELETE /resource_names/1.json
  def destroy
    @resource_name.destroy
    respond_to do |format|
      format.html { redirect_to resource_names_url, notice: 'Resource name was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resource_name
      @resource_name = ResourceName.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resource_name_params
      params.require(:resource_name).permit(:product_name, :product_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/resource_names_helper.rb
module ResourceNamesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GitProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/resource_names/_form.html.erb
<%= form_for(@resource_name) do |f| %>
  <% if @resource_name.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource_name.errors.count, "error") %> prohibited this resource_name from being saved:</h2>

      <ul>
      <% @resource_name.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_name %><br>
    <%= f.text_field :product_name %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.number_field :product_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resource_names/edit.html.erb
<h1>Editing resource_name</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource_name %> |
<%= link_to 'Back', resource_names_path %>

app/views/resource_names/index.html.erb
<h1>Listing resource_names</h1>

<table>
  <thead>
    <tr>
      <th>Product name</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resource_names.each do |resource_name| %>
      <tr>
        <td><%= resource_name.product_name %></td>
        <td><%= resource_name.product_id %></td>
        <td><%= link_to 'Show', resource_name %></td>
        <td><%= link_to 'Edit', edit_resource_name_path(resource_name) %></td>
        <td><%= link_to 'Destroy', resource_name, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resource name', new_resource_name_path %>

app/views/resource_names/new.html.erb
<h1>New resource_name</h1>

<%= render 'form' %>

<%= link_to 'Back', resource_names_path %>

app/views/resource_names/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product name:</strong>
  <%= @resource_name.product_name %>
</p>

<p>
  <strong>Product:</strong>
  <%= @resource_name.product_id %>
</p>

<%= link_to 'Edit', edit_resource_name_path(@resource_name) %> |
<%= link_to 'Back', resource_names_path %>